### ISSUE TITLE
Problem Statement and Goals Report Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#11]
**Todo**
- [ ] Review document for grammatical and spelling errors
- [ ] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/ProbStateGoalsDevPlan_Rubric.xlsx)
- [ ] Review [Checklist](https://github.com/arkinmodi/capstone/blob/main/docs/Checklists/ProbState-Checklist.pdf)
