### ISSUE TITLE
[VnV Plan] Verification and Validation Plan Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#138]
**Todo**
- [x] Review document for grammatical and spelling errors
- [x] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/VnVPlan.xlsx)
- [x] Review [VnV Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/VnV-Checklist.pdf)
