### ISSUE TITLE
[Design] [SD] System Design Documentation Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#327]
**Todo**
- [ ] Review document for grammatical and spelling errors
- [ ] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/DesDoc.xlsx)
- [ ] Review [Writing Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/Writing-Checklist.pdf)
