### ISSUE TITLE
[Design] [MG] Software Architecture Documentation Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#328]
**Todo**
- [x] Review document for grammatical and spelling errors
- [x] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/DesDoc.xlsx)
- [x] Review [MG Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/MG-Checklist.pdf)
- [x] Review [Writing Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/Writing-Checklist.pdf)
