### ISSUE TITLE
[VnV Report] Verification and Validation Report Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#434]
**Todo**
- [ ] Review document for grammatical and spelling errors
- [ ] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/VnVReport.xlsx)
- [ ] Review [Writing Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/Writing-Checklist.pdf)
