### ISSUE TITLE
[UG] User Guide Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#435]
**Todo**
- [ ] Review document for grammatical and spelling errors
- [ ] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics)
- [ ] Review [Writing Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/Writing-Checklist.pdf)
