### ISSUE TITLE
Meeting #23 - Feb 8, 2023

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#474]
**Meeting Time:** 2:30 PM
**Meeting Location:** ITB 237
**Meeting Agenda:**
- [x] Rev 0 Demo Presentation Prep
- [x] https://github.com/arkinmodi/project-sayyara/pull/321#discussion_r1099505109
- [x] https://github.com/arkinmodi/project-sayyara/pull/321#issuecomment-1421696616
- [ ] Schedule meeting with Nabeel for update (after Rev 0)?

**Comment by LeonSo7** [comment]
# Demo Outline
Simultaneously demo from user and shop perspective.

## Shop
* Mention we will not demo employee because it is similar to Shop Owner with less permissions
```
1. Signup / Login
2. Edit profile (add hours of operation)
3. Shop Manage > Show Employee List > Create a canned service and customs service
  * Mention that only shop owners can create, edit, and delete a service; but all employees can view
12. Show chat works from Shop view
13. Invite customer to schedule
16. Show appointment request
17. Accept appointment request
18. Show appointment request move to `Scheduled`
19.  Mark work order as in progress
21. Open and update work order
22. Mark work order as complete
```

## User
```
5. Sign up / Login
6. Show shop look up page and play around with filters
7. Click on shop created in `Step 2.`
8. See profile and click `request`
9. Create an appointment for canned job
10. Request quote for custom job
11. Show chat open and start chatting
15. Customer accepts invite to schedule and requests and appointment
16. Show appointment request tab
18. Show appointment request move to `Scheduled`
20. Show appointment moved to `In Progress`
23. Show appointment moved to `Complete`
```
## Plan for VnV


## Plans for Improving Documentation
* Update and revise documents to reflect changes
* Incorporate TA feedback into Rev1 docs

## Improvements
* Search filtering
  * Filter by location

## Out of scope improvements (Post Rev-1):
* Email (discussed with Nabeel)
  * Notifications
  * Employee invite
  * Password reset
* Images
* Web sockets
* Employee profile (discussed with Nabeel)

## TODO for demo:
* Have a document of inputs to copy paste
  * https://docs.google.com/document/d/15fSNjcSYnU3CCzsVyo_R8lgy18PXX_bVmqEMpqe6BIg/edit#
* Do we need demo for adding an employee?
* If we want to demo on 2 laptops, we need Vercel deployment working
* How to clear DB?
