### ISSUE TITLE
Software Requirements Specification Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#76]
**Todo**
- [ ] Review document for grammatical and spelling errors
- [ ] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/SRS.xlsx)
- [ ] Review [Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/SRS-Checklist.pdf)
