### ISSUE TITLE
Hazard Analysis Polishing

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#97]
**Todo**
- [x] Review document for grammatical and spelling errors
- [x] Review [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/HazAnalysis.xlsx)
- [x] Review [Writing Checklist](https://github.com/arkinmodi/project-sayyara/blob/main/docs/Checklists/Writing-Checklist.pdf)
- [x] https://github.com/arkinmodi/project-sayyara/pull/142#discussion_r996234474
